version: "3.1"
services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8090:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: main
      WORDPRESS_DB_PASSWORD: Aa123456
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: main
      MYSQL_PASSWORD: Aa123456
      MYSQL_RANDOM_ROOT_PASSWORD: Aa123456
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: